repos:
  # ---------------------------
  # 1. Standard Quality Hooks
  # ---------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-ast
      - id: check-added-large-files
        args: ["--maxkb=500"]

  # ---------------------------
  # 2. Ruff (Linter + Import Sorter)
  # ---------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        args: ["--fix"]

      - id: ruff-format

  # ---------------------------
  # 3. Black (Formatter)
  # ---------------------------
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.14

  # ---------------------------
  # 4. mypy (Static Typing)
  # ---------------------------
  #- repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: v1.11.1
  #  hooks:
  #    - id: mypy
  #      additional_dependencies:
  #        - types-PyYAML
  #        - types-requests
  #        - types-setuptools
  #      args: ["--ignore-missing-imports"]
  #

  # for html files
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.10
    hooks:
    - id: djhtml
      name: DjHTML
      entry: djhtml
      types: [html]
      language: python
      language_version: python3
      require_serial: true
      minimum_pre_commit_version: '2.9.0'
